// Users

export const FETCH_USER = 'FETCH_USER';
export const BECOME_PROVIDER = 'BECOME_PROVIDER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const LINK_PROVIDER = 'LINK_PROVIDER';
export const REJECT_CANDIDATE_PROVIDER = 'REJECT_CANDIDATE_PROVIDER';
export const ADD_CANDIDATE_PROVIDER = 'ADD_CANDIDATE_PROVIDER';
export const ACCEPT_CANDIDATE_PROVIDER = 'ACCEPT_CANDIDATE_PROVIDER';

// Organizations

export const FIND_ORGANIZATION = 'FIND_ORGANIZATION';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const FETCH_ORGANIZATION = 'FETCH_ORGANIZATION';
export const GET_USER_ORGANIZATION = 'GET_USER_ORGANIZATION';
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const GET_PROVIDER_ORGANIZATION = 'GET_PROVIDER_ORGANIZATION';
export const LINK_USER = 'LINK_USER';
export const CLEAR_ORGANIZATIONS = 'CLEAR_ORGANIZATIONS';
export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';
export const GET_ORGANIZATION = 'GET_ORGANIZATION';